---
- hosts: web
  become: yes

  tasks:

    - name: Update packages
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - git
          - curl
        state: present

    - name: Install NodeJS
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
        apt-get install -y nodejs

    - name: Clone repository
      git:
        repo: "https://github.com/UnpredictablePrashant/TravelMemory.git"
        dest: /home/ubuntu/TravelMemory
        force: yes

    - name: Install backend dependencies
      shell: |
        cd /home/ubuntu/TravelMemory/backend
        npm install

    - name: Install frontend dependencies
      shell: |
        cd /home/ubuntu/TravelMemory/frontend
        npm install
